SCREEN_TITLE = "PyGame Boilerplate"

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

DEFAULT_SPRITE_SIZE = (16, 16)
DEFAULT_SPRITE_COLOR = (255, 255, 255)

DEFAULT_GRAVITY_ACCELERATION = (0, 0)
DEFAULT_FRICTION = (1, 1)

FPS = 60
